/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE subjectsBaseService PLEASE EDIT ../subjects.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Subjects } from '../../domain/school-management-system_db/subjects';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Subjects.service.ts
 */

/*
 * SCHEMA DB Subjects
 *
	{
		SubjectName: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Subjects: {
			type: Schema.ObjectId,
			ref : "ExamResults"
		},
		_Subjects: [{
			type: Schema.ObjectId,
			ref : "Student"
		}],
		_Subjects: [{
			type: Schema.ObjectId,
			ref : "Teacher"
		}],
	}
 *
 */
@Injectable()
export class SubjectsBaseService {

    contextUrl: string = environment.endpoint + '/subjects';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * SubjectsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Subjects): Observable<Subjects> {
        return this.http
            .post<Subjects>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * SubjectsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SubjectsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Subjects> {
        return this.http
            .get<Subjects>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SubjectsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Subjects[]> {
        return this.http
            .get<Subjects[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * SubjectsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Subjects): Observable<Subjects> {
        return this.http
            .post<Subjects>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
